#pragma once
#include "CoreMinimal.h"
#include "Stats/Stats.h"
#include "ProfilingDebugging/CpuProfilerTrace.h"

DECLARE_STATS_GROUP(TEXT("ACE Client"), STATGROUP_ACE, STATCAT_Advanced);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Network / dispatch"), STAT_ACENetwork, STATGROUP_ACE, ACECLIENT_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("World presentation"), STAT_ACEWorld, STATGROUP_ACE, ACECLIENT_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Terrain presentation"), STAT_ACETerrain, STATGROUP_ACE, ACECLIENT_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Portal visibility"), STAT_ACEVisibility, STATGROUP_ACE, ACECLIENT_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Remote movement / ground"), STAT_ACERemote, STATGROUP_ACE, ACECLIENT_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Character animation"), STAT_ACEAnimation, STATGROUP_ACE, ACECLIENT_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Appearance construction"), STAT_ACEAppearance, STATGROUP_ACE, ACECLIENT_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Scripts / particles / lights"), STAT_ACEEffects, STATGROUP_ACE, ACECLIENT_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("HUD refresh"), STAT_ACEHUD, STATGROUP_ACE, ACECLIENT_API);

DECLARE_CYCLE_STAT_EXTERN(TEXT("Sky presentation"), STAT_ACESky, STATGROUP_ACE, ACECLIENT_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Sky fog / world materials"), STAT_ACESkyFog, STATGROUP_ACE, ACECLIENT_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Sky world lighting"), STAT_ACESkyLighting, STATGROUP_ACE, ACECLIENT_API);

#define ACE_PROFILE_SCOPE(Name) SCOPE_CYCLE_COUNTER(STAT_ACE##Name); TRACE_CPUPROFILER_EVENT_SCOPE(ACE_##Name)
