#include "ACEProfiling.h"
DEFINE_STAT(STAT_ACENetwork);
DEFINE_STAT(STAT_ACEWorld);
DEFINE_STAT(STAT_ACETerrain);
DEFINE_STAT(STAT_ACEVisibility);
DEFINE_STAT(STAT_ACERemote);
DEFINE_STAT(STAT_ACEAnimation);
DEFINE_STAT(STAT_ACEAppearance);
DEFINE_STAT(STAT_ACEEffects);
DEFINE_STAT(STAT_ACEHUD);
DEFINE_STAT(STAT_ACESky);
DEFINE_STAT(STAT_ACESkyFog);
DEFINE_STAT(STAT_ACESkyLighting);
