// Auto-generated from ACE.Entity CharacterTitle.cs — do not hand-edit.
static const TCHAR* GetCharacterTitleName(uint32 TitleId)
{
	static const TCHAR* Names[] = {
		TEXT("Invalid"),
		TEXT("Adventurer"),
		TEXT("Archer"),
		TEXT("Blademaster"),
		TEXT("Enchanter"),
		TEXT("Life Mage"),
		TEXT("Sorcerer"),
		TEXT("Vagabond"),
		TEXT("Warrior"),
		TEXT("Bow Hunter"),
		TEXT("Life Caster"),
		TEXT("Soldier"),
		TEXT("Swashbuckler"),
		TEXT("War Mage"),
		TEXT("Wayfarer"),
		TEXT("Abhorrent Warrior"),
		TEXT("Alchemist"),
		TEXT("Annihilator"),
		TEXT("Apothecary"),
		TEXT("Arctic Adventurer"),
		TEXT("Arctic Mattekar Annihilator"),
		TEXT("Artifex"),
		TEXT("Axe Warrior"),
		TEXT("Ballisteer"),
		TEXT("Baneofthe Remoran"),
		TEXT("Blood Shreth Butcher"),
		TEXT("Bloodletter"),
		TEXT("Broodu Killer"),
		TEXT("Browerk Killer"),
		TEXT("Bug Butcher"),
		TEXT("Bugstomper"),
		TEXT("Bunny Master"),
		TEXT("Carenzi Slayer"),
		TEXT("Chain Breaker"),
		TEXT("Championof Dereth"),
		TEXT("Championof Sanamar"),
		TEXT("Championof Silyun"),
		TEXT("Chef"),
		TEXT("Creature Adept"),
		TEXT("Dagger Fighter"),
		TEXT("Deadeye"),
		TEXT("Deathcap Defeater"),
		TEXT("Defenderof Dereth"),
		TEXT("Deliverer"),
		TEXT("Diplomat"),
		TEXT("Dire Mattekar Dispatcher"),
		TEXT("Duelist"),
		TEXT("Ebon Gromnie Eradicator"),
		TEXT("Engorged Scourge"),
		TEXT("Evoker"),
		TEXT("Explorer"),
		TEXT("Exterminator"),
		TEXT("Fisherman"),
		TEXT("Fletcher"),
		TEXT("Floeshark Flogger"),
		TEXT("Friendof Sanamar"),
		TEXT("Friendof Silyun"),
		TEXT("Gaerlan Slayer"),
		TEXT("Gardener Weeder"),
		TEXT("Glenden Wood Knight"),
		TEXT("Glenden Wood Militia"),
		TEXT("Golden God"),
		TEXT("Grave Robber"),
		TEXT("Guardianof Dereth"),
		TEXT("Gumshoe"),
		TEXT("Guppy Master"),
		TEXT("Heart Ripper"),
		TEXT("Heroof Dereth"),
		TEXT("Heroof Sanamar"),
		TEXT("Heroof Silyun"),
		TEXT("Honorary Snowman"),
		TEXT("Honorary Windreave"),
		TEXT("Hunter"),
		TEXT("Impaler"),
		TEXT("Insatiable Slayer"),
		TEXT("Invaders Bane"),
		TEXT("Iron Chef"),
		TEXT("Iron Spined Chittick Immolator"),
		TEXT("Item Adept"),
		TEXT("Keeperof Dereth"),
		TEXT("Keerik Killer"),
		TEXT("Kingslayer"),
		TEXT("Kiree Killer"),
		TEXT("Knath Andras Assassinator"),
		TEXT("Lakeman"),
		TEXT("Life Adept"),
		TEXT("Lightbringer"),
		TEXT("Mace Warrior"),
		TEXT("Man At Arms Thrasher"),
		TEXT("Master Fletcher"),
		TEXT("Masterof Slaughter"),
		TEXT("Masterof Staves"),
		TEXT("Miner"),
		TEXT("Moarsman Defiler"),
		TEXT("Morale Smasher"),
		TEXT("Mosswart Worshipper Whipper"),
		TEXT("Mottled Carenzi Mauler"),
		TEXT("Mud Slinger"),
		TEXT("Naughty Skeleton Snuffer"),
		TEXT("Olthoi Ripper Reducer"),
		TEXT("Paragonof Death"),
		TEXT("Philanthropist"),
		TEXT("Plate Armoredillo Punisher"),
		TEXT("Platinum Prowler"),
		TEXT("Polar Ursuin Pounder"),
		TEXT("Polardillo Pummeler"),
		TEXT("Pond Scum"),
		TEXT("Pro Fisherman"),
		TEXT("Projectilist"),
		TEXT("Pugilist"),
		TEXT("Queenslayer"),
		TEXT("Ravenous Killer"),
		TEXT("Red Fury"),
		TEXT("Reeshan Killer"),
		TEXT("Rehir Killer"),
		TEXT("Repugnant Eater Ripper"),
		TEXT("Resistance Fighter"),
		TEXT("Resistance Recruit"),
		TEXT("Servantof The Deep"),
		TEXT("Sezzherei Slayer"),
		TEXT("Shadow Stalker"),
		TEXT("Shallows Shark Nemesis"),
		TEXT("Sharpshooter"),
		TEXT("Shellfish Hater"),
		TEXT("Shieldof Glenden"),
		TEXT("Shredder"),
		TEXT("Silver Serf"),
		TEXT("Siraluun Slasher"),
		TEXT("Skipper"),
		TEXT("Skullcrusher"),
		TEXT("Skullsplitter"),
		TEXT("Slicer"),
		TEXT("Sniper"),
		TEXT("Soldier Slaughterer"),
		TEXT("Spear Warrior"),
		TEXT("Spring Cleaner"),
		TEXT("Staff Warrior"),
		TEXT("Stonebreaker"),
		TEXT("Sureshot"),
		TEXT("Swordfighter"),
		TEXT("Theurgist"),
		TEXT("Thrungus Reaper"),
		TEXT("Timberman"),
		TEXT("Tracker"),
		TEXT("Trapper"),
		TEXT("Tukora Lieutenant Trouncer"),
		TEXT("Unarmed Brawler"),
		TEXT("Violator Grievver Vetoer"),
		TEXT("Voracious Flayer"),
		TEXT("Voracious Hunter"),
		TEXT("War Adept"),
		TEXT("Wardenof Dereth"),
		TEXT("Warlock"),
		TEXT("Warlordof Dereth"),
		TEXT("Warrior Vanquisher"),
		TEXT("Wicked Skeleton Walloper"),
		TEXT("Windreave Stalker"),
		TEXT("Worker Obliterator"),
		TEXT("Dryreach Militia"),
		TEXT("Honorary Shadow Hunter"),
		TEXT("Perforated Knight"),
		TEXT("Pest Control"),
		TEXT("Rat Reaper"),
		TEXT("Nymph Maniac"),
		TEXT("Simiu S"),
		TEXT("Second Place Lore Quiz Night"),
		TEXT("A C Veteran"),
		TEXT("Aintafraidofnoghost"),
		TEXT("Aintafraidofnoghosttwo"),
		TEXT("Aintafraidofnoghostthree"),
		TEXT("Ankle Biter"),
		TEXT("Annoying Furry Talking Animal"),
		TEXT("Archer Assassin"),
		TEXT("Archmage"),
		TEXT("Asherons Call God"),
		TEXT("Avatarof Kain"),
		TEXT("Azure Assailant"),
		TEXT("Baby Bunny Master"),
		TEXT("Baron Oddity"),
		TEXT("Beginningofthe End"),
		TEXT("Best Meleein D T"),
		TEXT("Big Block"),
		TEXT("Big Rocx"),
		TEXT("Blood"),
		TEXT("Bounty Hunter"),
		TEXT("British Tootsie"),
		TEXT("Bug Bait"),
		TEXT("Bunny Killer"),
		TEXT("Carebear Stare"),
		TEXT("Certified Ganksta"),
		TEXT("Chicken Nugget"),
		TEXT("Chicken Select"),
		TEXT("Chimaeras Champion"),
		TEXT("Co Monarchof The Chosen"),
		TEXT("Containment Unit"),
		TEXT("Coolest Title Ever"),
		TEXT("Corrosive Soul"),
		TEXT("Cow Killer"),
		TEXT("Cowboy"),
		TEXT("Crystal Lord King"),
		TEXT("Cuddly Kitten"),
		TEXT("Curmudgeons Friend"),
		TEXT("Cursed Adventurer"),
		TEXT("Dagger Master"),
		TEXT("Dark Sword Lady"),
		TEXT("Darktides Finest"),
		TEXT("Darktides Most Wanted"),
		TEXT("Dead Meat"),
		TEXT("Deadly Eggburt"),
		TEXT("Deathby Default"),
		TEXT("Deathby Pumpkin"),
		TEXT("Deathby Sappho"),
		TEXT("Death Specialist"),
		TEXT("Defenderof Mr P"),
		TEXT("Dereths Gladiator"),
		TEXT("Dereths Master Dodger"),
		TEXT("Dev Evader"),
		TEXT("Dev Killer"),
		TEXT("Dev Slayer"),
		TEXT("Double Fashion King"),
		TEXT("Double Golem Killer"),
		TEXT("Double Survival Champion"),
		TEXT("Dudeof D O O M"),
		TEXT("Ecto Cooler"),
		TEXT("Ecto Coolertwo"),
		TEXT("Envoy Slayer"),
		TEXT("Escapee Killer"),
		TEXT("Evil Toothfairy"),
		TEXT("Fancy Title"),
		TEXT("Fashion King"),
		TEXT("Fashion Penguin King"),
		TEXT("Fashion Queen"),
		TEXT("Fashion Victim"),
		TEXT("Fearless Fighter"),
		TEXT("Flag Boy"),
		TEXT("Frelorn Slayer"),
		TEXT("Friendto Mr P"),
		TEXT("Gangsta Style"),
		TEXT("Gangster"),
		TEXT("Ghostbuster"),
		TEXT("Gimp"),
		TEXT("Gimp Goddess"),
		TEXT("Gimpy Mageof Might"),
		TEXT("Gladiator Champion"),
		TEXT("Glowing Archer"),
		TEXT("Godofthe Swordsman"),
		TEXT("Golem Killer"),
		TEXT("Golem Slayer"),
		TEXT("Great Pookie Slayer"),
		TEXT("Guardian Angel"),
		TEXT("Guardianof Arwic"),
		TEXT("Hamster Herder"),
		TEXT("Hamster Vitae"),
		TEXT("Have Bunnies Will Travel"),
		TEXT("Have Trike Will Babble"),
		TEXT("Hideand Seek Specialist"),
		TEXT("Hollywood Bud"),
		TEXT("Holtburg Survival Champion"),
		TEXT("Holtburgs Survivor Champion"),
		TEXT("Honorary Pink Eep"),
		TEXT("Hungry Hungry Hippo"),
		TEXT("Husbandof Lynnie"),
		TEXT("Husbands Healer"),
		TEXT("Iam Big P I M P I N"),
		TEXT("Ilikeddying"),
		TEXT("Jessica Heart"),
		TEXT("Kingofallthatis Pumpkin"),
		TEXT("Kingof Caul"),
		TEXT("Kingof Darktide"),
		TEXT("Kingof Pierce Diggys"),
		TEXT("Knight Rider"),
		TEXT("Ladyofthe Four Towers"),
		TEXT("Lange Gang"),
		TEXT("Level Master"),
		TEXT("Leviathan"),
		TEXT("Leviathan Slayer"),
		TEXT("Libe Events Manager"),
		TEXT("Life Preserver"),
		TEXT("Live Event Coordinator"),
		TEXT("Live Events Manager"),
		TEXT("Live Op Coordinator"),
		TEXT("Lore Second Place"),
		TEXT("Lore Second Place Quiz Night"),
		TEXT("Lore Champion Quiz Night1"),
		TEXT("Lore Champion Quiz Night2"),
		TEXT("Lore Master"),
		TEXT("Lore Master Quiz Night1"),
		TEXT("Lore Master Quiz Night2"),
		TEXT("Lore Master Second Place"),
		TEXT("Lore Masterof Staves"),
		TEXT("Lotsof Vitae"),
		TEXT("Lucky Lady"),
		TEXT("Mad Cow Slayer"),
		TEXT("Mages Assitant"),
		TEXT("Master Tinkerer"),
		TEXT("Mayorof Ayan Baqur"),
		TEXT("Minty Fresh"),
		TEXT("Misunderstood Pengy"),
		TEXT("Mom"),
		TEXT("Mommy Pengy"),
		TEXT("Mosswart Ally"),
		TEXT("Mr Nice Guy"),
		TEXT("Murderer"),
		TEXT("Murderertwo"),
		TEXT("Newby Title"),
		TEXT("Nice Blue Lady"),
		TEXT("Numberonedraftpick"),
		TEXT("Old School"),
		TEXT("Paradox Slayer"),
		TEXT("Patron Saintofthe Lifestone"),
		TEXT("Peacebear"),
		TEXT("Penguin Killer"),
		TEXT("Pig Farmer"),
		TEXT("Pink Bunny Killer"),
		TEXT("Pink Bunny Master"),
		TEXT("Pink Goddess"),
		TEXT("Pink Lady"),
		TEXT("P K Queen"),
		TEXT("Playa Killa King"),
		TEXT("Pokemon Slayer"),
		TEXT("Pretty Pumpkin"),
		TEXT("Prisoner"),
		TEXT("Protectorofthe Cheese"),
		TEXT("Proton Pack"),
		TEXT("Pumpkin Slayer"),
		TEXT("Pumpkin Stalker"),
		TEXT("Purple Pengy"),
		TEXT("Pwnerof Newbs"),
		TEXT("Queenof Brats"),
		TEXT("Queens Crafter"),
		TEXT("Queens Craftertwo"),
		TEXT("Queens Pack Rat"),
		TEXT("Queens Packrat"),
		TEXT("Queens Tinker"),
		TEXT("Rawr"),
		TEXT("Raynes Mage Pet"),
		TEXT("Reggae Renegade"),
		TEXT("Ring Bearer"),
		TEXT("Ringringring Bananaphone"),
		TEXT("Road Kill"),
		TEXT("Rolling Death Destroyer"),
		TEXT("Royal Chef"),
		TEXT("Royal Cook"),
		TEXT("Rugged"),
		TEXT("Sanitation Engineer"),
		TEXT("Scarecrow Slayer"),
		TEXT("Scary Pumkpkin Dominator"),
		TEXT("Scary Pumpkin Slayer"),
		TEXT("Sentinal"),
		TEXT("Sentry"),
		TEXT("Shadow Child"),
		TEXT("Shadow Hunter"),
		TEXT("Shadow Slayer"),
		TEXT("Slayerofthe Great Pookie"),
		TEXT("Slimer"),
		TEXT("Snazzy Dresser"),
		TEXT("Soul Man"),
		TEXT("Spooky Title"),
		TEXT("Staff Masta"),
		TEXT("Staypuffed Mallow Girl"),
		TEXT("Super Gimped Adventurer"),
		TEXT("Supercalifragilisticexpialidocious"),
		TEXT("Superman"),
		TEXT("Survivor Champion"),
		TEXT("Sword Scholar"),
		TEXT("Teh Newb"),
		TEXT("Teh Saint"),
		TEXT("Testing Guy"),
		TEXT("The Bait"),
		TEXT("The Chosen King"),
		TEXT("The Come Back Kid"),
		TEXT("The Forgotten"),
		TEXT("The Gimped"),
		TEXT("The Greatand Powerful"),
		TEXT("The Half Fox"),
		TEXT("The Noob"),
		TEXT("The Purple Fez"),
		TEXT("The Pwnerer"),
		TEXT("The Unknown Pk"),
		TEXT("Thunder Chicken Slayer"),
		TEXT("T M Killer"),
		TEXT("Tough Guy"),
		TEXT("Tradesmanof Auberean"),
		TEXT("Treasure Hunter"),
		TEXT("Tremendous Monouga Master"),
		TEXT("Triple Golem Killer"),
		TEXT("Turbine Slayer"),
		TEXT("Twinsof Terror"),
		TEXT("Uberest Noobon Frostfell"),
		TEXT("Underworld Thugg"),
		TEXT("Viamontian Slayer"),
		TEXT("Vitae King"),
		TEXT("Vitae Vixen"),
		TEXT("Vixenof Vitae"),
		TEXT("Wabbit Bait"),
		TEXT("Wabbit Killer"),
		TEXT("Wandering Fool"),
		TEXT("Wardens Assistant"),
		TEXT("Wardens Thug"),
		TEXT("Wimp"),
		TEXT("Wolfpack Crafter"),
		TEXT("Wonder Woman"),
		TEXT("Yagotserved"),
		TEXT("G I M Pcaps"),
		TEXT("Wardens Assistanttwo"),
		TEXT("Supreme Bunny Master"),
		TEXT("Guardianofthe Dark"),
		TEXT("Aprils Fool"),
		TEXT("Ulgrims Eep"),
		TEXT("Mukkir Masher"),
		TEXT("Harbingers Bane"),
		TEXT("Masterofthe Elements"),
		TEXT("Killcranes Ally"),
		TEXT("Apprentice Shadow Hunter"),
		TEXT("Squireofthe Golden Flame"),
		TEXT("Knightofthe Golden Flame"),
		TEXT("Knightofthe Whispering Blade"),
		TEXT("The Black Spear"),
		TEXT("Carraidas Avenger"),
		TEXT("Paragonofthe Whispering Blade"),
		TEXT("Paragonofthe Rossu Morta"),
		TEXT("Chosenof Varicci"),
		TEXT("Chosenof Elysa"),
		TEXT("Small Mukkir Squasher"),
		TEXT("Blood Warrior"),
		TEXT("Strategist"),
		TEXT("War Beast"),
		TEXT("Championof Daemal"),
		TEXT("Heroofthe Golden Flame"),
		TEXT("Slayerofthe Black Spear"),
		TEXT("Obviously Bored"),
		TEXT("Zefir Zapper"),
		TEXT("Tusker Blight"),
		TEXT("Elemental Eradicator"),
		TEXT("Expert Banished Hunter"),
		TEXT("Expert Fallen Hunter"),
		TEXT("Elite Head Hunter"),
		TEXT("Friendofthe Frostglaive"),
		TEXT("Squireof New Viamont"),
		TEXT("Reanimator"),
		TEXT("Zombie Incursion Survivor"),
		TEXT("Ulgrims Drinking Buddy"),
		TEXT("Masterofthe Porcelain Altar"),
		TEXT("Masterofthe Mystical Mug"),
		TEXT("Colosseum Champion"),
		TEXT("Titan"),
		TEXT("Colossus"),
		TEXT("Master Gladiator"),
		TEXT("Fearless"),
		TEXT("Lordofthe Arena"),
		TEXT("Ring Master"),
		TEXT("Pit Fighter"),
		TEXT("Myrmidon"),
		TEXT("Hostile Combatant"),
		TEXT("Survivalist"),
		TEXT("Warriorofthe Seventh Circle"),
		TEXT("Gladiator"),
		TEXT("Contender"),
		TEXT("Drudge Dread"),
		TEXT("Arena Custodian"),
		TEXT("Arena Rat"),
		TEXT("Scrapper"),
		TEXT("Champion Ring I I I"),
		TEXT("Champion Ring V"),
		TEXT("Champion Ring V I"),
		TEXT("Champion Ring V I I"),
		TEXT("Champion Ring X I I"),
		TEXT("Master Champion Ring X"),
		TEXT("Ruuk Ally"),
		TEXT("Seekerof Asheron"),
		TEXT("Seekerof Torgluuk"),
		TEXT("Portal Ritualist"),
		TEXT("Ranger Ruuk"),
		TEXT("Basher Slasher"),
		TEXT("Guruk Hunter"),
		TEXT("Dead Eyeforthe Colossi"),
		TEXT("Fiendish Huntsman"),
		TEXT("Monster Killer"),
		TEXT("Bosh Bosh Kibosh"),
		TEXT("Mushroom Collector"),
		TEXT("Fungal Farmer"),
		TEXT("Mushroom Man"),
		TEXT("Fungi"),
		TEXT("Mushroom King"),
		TEXT("Thrungamandius"),
		TEXT("Initiateofthe Blade"),
		TEXT("Torgluuks Liberator"),
		TEXT("Burun Liberator"),
		TEXT("Asherons Savior"),
		TEXT("Asherons Defender"),
		TEXT("Fuzzy Bunny Slayer"),
		TEXT("Moar Hunter"),
		TEXT("Spiketooth Slayer"),
		TEXT("Tower Guardian Architect"),
		TEXT("Artisanofthe Flameand Light"),
		TEXT("Guardianofthe Tower"),
		TEXT("Cragstone Militia"),
		TEXT("Cragstone Knight"),
		TEXT("Guardianof Cragstone"),
		TEXT("Knightofthe Windmill"),
		TEXT("Hero Of House Mhoire"),
		TEXT("Lady Tairlas Champion"),
		TEXT("Royal Investigator"),
		TEXT("Wanga Fighter"),
		TEXT("Hoogans Hero"),
		TEXT("Cragstone Firefighter"),
		TEXT("Stalker Stalker"),
		TEXT("Ravenous"),
		TEXT("Altered Hunter"),
		TEXT("Augmented Hunter"),
		TEXT("Drudge Doom"),
		TEXT("Defenderof Kryst"),
		TEXT("Paradoxtouched Queenslayer"),
		TEXT("Amelias Caretaker"),
		TEXT("Prodigal Tusker Slayer"),
		TEXT("Mudmouths Bane"),
		TEXT("Oolutangas Bane"),
		TEXT("Prodigal Shadow Slayer"),
		TEXT("Prodigal Harbinger Slayer"),
		TEXT("Blood Seeker"),
		TEXT("Storm Rider"),
		TEXT("Meddler"),
		TEXT("Vile Betrayer"),
		TEXT("Spy"),
		TEXT("Slithis Slayer"),
		TEXT("Chosenofthe Rift"),
		TEXT("Rift Shifter"),
		TEXT("Rift Walker"),
		TEXT("Reef Builder"),
		TEXT("Reef Breaker"),
		TEXT("Crypt Rat"),
		TEXT("Grave Stalker"),
		TEXT("Bone Breaker"),
		TEXT("Crypt Creeper"),
		TEXT("Tomb Raider"),
		TEXT("Followerofthe Vine"),
		TEXT("Harvester"),
		TEXT("Harvester Harvester"),
		TEXT("Harvester Harvester Harvester"),
		TEXT("Pumpkin Throne Usurper"),
		TEXT("Death Knight"),
		TEXT("Null Title"),
		TEXT("Tracker Guardian"),
		TEXT("Dojiro Sangis Savior"),
		TEXT("Masterofthe Hunt"),
		TEXT("Initiateofthe Hunt"),
		TEXT("Apprenticeofthe Hunt"),
		TEXT("Discipleofthe Hunt"),
		TEXT("Seekerofthe Hunt"),
		TEXT("Championofthe Hunt"),
		TEXT("Guardianof Linvak Tukal"),
		TEXT("Unwitting Participant"),
		TEXT("Friendof Rheaga"),
		TEXT("Slayerof Rheaga"),
		TEXT("Protectorofthe Past"),
		TEXT("Warriorofthe Past"),
		TEXT("Anthropologist"),
		TEXT("Gold Farmer"),
		TEXT("Third Eye Blinder"),
		TEXT("Dire Drudge Decapitator"),
		TEXT("Renegade Hunter"),
		TEXT("Banderling Bully"),
		TEXT("Xenophobic"),
		TEXT("Shadow Sunderer"),
		TEXT("Dire Huntsman"),
		TEXT("Game Warden"),
		TEXT("Honorary Reaofthe Aun"),
		TEXT("Hopeofthe Past"),
		TEXT("Beaconof Hope"),
		TEXT("Aerbaxs Bane"),
		TEXT("Aerbax Slayer"),
		TEXT("Jesters Emancipator"),
		TEXT("Jesters Fool"),
		TEXT("Jesters Accomplice"),
		TEXT("Honorary Burun Scout"),
		TEXT("Marble Wrangler"),
		TEXT("Secret Keeper"),
		TEXT("Jesters Little Helper"),
		TEXT("Hard To Kill"),
		TEXT("Expendable"),
		TEXT("Noviceofthe Sea"),
		TEXT("Acolyteofthe Sea"),
		TEXT("Ministerofthe Sea"),
		TEXT("Defenderofthe Sea"),
		TEXT("Championofthe Sea"),
		TEXT("Masterofthe Sea"),
		TEXT("Defeater Of The Blight"),
		TEXT("Championofthe Aerlinthe Node"),
		TEXT("Championofthe Amun Node"),
		TEXT("Championofthe Esper Node"),
		TEXT("Championofthe Halaetan Node"),
		TEXT("Championofthe Linvak Node"),
		TEXT("Championofthe Obsidian Node"),
		TEXT("Ulgrims Happy Hundredth"),
		TEXT("Pluckerof Eyes"),
		TEXT("Wardenofthe Burning Wood"),
		TEXT("Tough Tough"),
		TEXT("Archaeologist"),
		TEXT("Heroof Woe"),
		TEXT("Defenderof Silyun"),
		TEXT("Memorial Champion"),
		TEXT("Thaneof Colier"),
		TEXT("Guardianofthe Keep"),
		TEXT("Warriorofthe Crater Lake"),
		TEXT("Arwician"),
		TEXT("Desert Warrior"),
		TEXT("Mayoi Protector"),
		TEXT("Stone Collector"),
		TEXT("Rock Star"),
		TEXT("Rock Hound"),
		TEXT("Warriorof Woe"),
		TEXT("Haswaytoomuchtime"),
		TEXT("Champion Immemorial"),
		TEXT("Colier Miner"),
		TEXT("Legionnaire"),
		TEXT("Volcanologist"),
		TEXT("Hilltop Defender"),
		TEXT("Arwic Noble"),
		TEXT("Zharalim"),
		TEXT("Samurai"),
		TEXT("Guardianinthe Patriarch Raids"),
		TEXT("Wardeninthe Patriarch Raids"),
		TEXT("Heroofthe Patriarch Raids"),
		TEXT("Markedbythe Patriarchs"),
		TEXT("Cathedrals Champion"),
		TEXT("Asherons Militia"),
		TEXT("Minik Ras Bane"),
		TEXT("Kazyk Ris Bane"),
		TEXT("Nivinizks Bane"),
		TEXT("Minik Ras Nemesis"),
		TEXT("Kazyk Ris Nemesis"),
		TEXT("Nivinizks Nemesis"),
		TEXT("Aubereans Sentinel"),
		TEXT("Dereths Elite"),
		TEXT("Defenderofthe Deru"),
		TEXT("Baneofthe Blessed"),
		TEXT("Negotiator"),
		TEXT("Baneofthe Blight"),
		TEXT("Gifted"),
		TEXT("Seasonal Seeker"),
		TEXT("Amateur Explorer"),
		TEXT("Experienced Explorer"),
		TEXT("Adept Explorer"),
		TEXT("Master Explorer"),
		TEXT("Elite Explorer"),
		TEXT("Mountain Climber"),
		TEXT("Daredevil"),
		TEXT("Sky Diver"),
		TEXT("Spelunker"),
		TEXT("Party Goer"),
		TEXT("Crater Crasher"),
		TEXT("Tactical Aid"),
		TEXT("True Tactician"),
		TEXT("Tactical Fantastical"),
		TEXT("Fireofthe Tanada"),
		TEXT("Crystalline Adventurer"),
		TEXT("Wisp Whipper"),
		TEXT("Burning Soul"),
		TEXT("Frozen Fighter"),
		TEXT("Dedicated"),
		TEXT("Assassin"),
		TEXT("Death Dealer"),
		TEXT("Bridge Jumper"),
		TEXT("Sure Step"),
		TEXT("Player Slayer"),
		TEXT("Bathedin Blood"),
		TEXT("I Am Darktide"),
		TEXT("Darknessinthe Light"),
		TEXT("Beginnings End"),
		TEXT("Nexus Crawler"),
		TEXT("Selfless Soul"),
		TEXT("Timeless Adventurer"),
		TEXT("Virindi Informer"),
		TEXT("No Cage Could Hold Me"),
		TEXT("Allfor One"),
		TEXT("Onefor All"),
		TEXT("Jack O All Trades"),
		TEXT("Knightofthe Northeast Tower"),
		TEXT("Knightofthe Northwest Tower"),
		TEXT("Knightofthe Southeast Tower"),
		TEXT("Knightofthe Southwest Tower"),
		TEXT("Knightofthe Mhoire Throne"),
		TEXT("Historianofthe Mhoire Throne"),
		TEXT("Championof House Mhoire"),
		TEXT("Swordbearerof House Mhoire"),
		TEXT("Archmageof House Mhoire"),
		TEXT("Seekerof Castle Mhoire"),
		TEXT("Stewardof Castle Mhoire"),
		TEXT("Golden Gear Crafter"),
		TEXT("Allyofthe Gold Primus"),
		TEXT("Gear Knight Assassin"),
		TEXT("Gear Knight Recruiter"),
		TEXT("Gear Knight Emissary"),
		TEXT("Menhir Seeker"),
		TEXT("Mana Field Finder"),
		TEXT("Assistants Assistant"),
		TEXT("Arcanum Adventurer"),
		TEXT("Gear Knight Defender"),
		TEXT("Ripper"),
		TEXT("Acid Spitter"),
		TEXT("Bloodstone Hunter"),
		TEXT("Guiding Light"),
		TEXT("Clouded Soul"),
		TEXT("Undercoverof Darkness"),
		TEXT("Broughtto Light"),
		TEXT("Illuminatingthe Shadows"),
		TEXT("Exploring Archaeologist"),
		TEXT("Contract Killer"),
		TEXT("Shadow Puppet"),
		TEXT("Hopebringer"),
		TEXT("Inthe Dark"),
		TEXT("Searching Shadows"),
		TEXT("Shadow Soldier"),
		TEXT("Bright Knight"),
		TEXT("Merciful Killer"),
		TEXT("Soul Siphon"),
		TEXT("The Tou Tou Terror"),
		TEXT("Double Agent"),
		TEXT("Duleingwiththe Dark"),
		TEXT("Creatureof Chaos"),
		TEXT("Conspirator"),
		TEXT("Heroofthe Night"),
		TEXT("Masterofthe Twisted Word"),
		TEXT("The Nightmare Lord"),
		TEXT("The Nightmare Mage"),
		TEXT("The Twisted Weaver"),
		TEXT("Lordof Dark Dreams"),
		TEXT("The Dark Dreamwalker"),
		TEXT("The Dreamslayer"),
		TEXT("The Nightmare Stalker"),
		TEXT("The Thought Spiral"),
		TEXT("Masterofthe Oubliette"),
		TEXT("The Restless"),
		TEXT("Fiery Spirit"),
		TEXT("Icy Veins"),
		TEXT("Shocking Disposition"),
		TEXT("Acidic Soul"),
		TEXT("Grounded Morals"),
		TEXT("Darkened Heart"),
		TEXT("The True Emperor"),
		TEXT("Bearerof Darkness"),
		TEXT("Healer Ritualist"),
		TEXT("Vanquisherofthe Titan"),
		TEXT("Derethian Newbie"),
		TEXT("Novice Wanderer"),
		TEXT("Notable Citizen"),
		TEXT("Adept Adventurer"),
		TEXT("Intrepid Explorer"),
		TEXT("Supreme Soldier"),
		TEXT("Epic Warrior"),
		TEXT("Paragonof New Aluvia"),
		TEXT("An Auberean Legend"),
		TEXT("Heretic"),
		TEXT("Captain"),
		TEXT("Pet Savior"),
		TEXT("Avalanche Avoider"),
		TEXT("Liberatorof Uziz"),
		TEXT("Outof Tune"),
		TEXT("Hive Queenslayer"),
		TEXT("Eviscerator Decimator"),
		TEXT("Ultimate Warrior"),
		TEXT("Stone Cold Killer"),
		TEXT("Quellerof Rage"),
		TEXT("Enderof Torment"),
		TEXT("Controllerof Emotions"),
		TEXT("Rynthid Ravager"),
		TEXT("Lothus Servitor"),
		TEXT("Allyofthe Lothus"),
		TEXT("Allyofthe Council"),
		TEXT("Emotional Wreck"),
		TEXT("Minion Marauder"),
		TEXT("Rynthid Wrecker"),
		TEXT("Night Owl"),
		TEXT("Menderofthe Rift"),
		TEXT("Sorcerer Slayer"),
		TEXT("Rage Quitter"),
		TEXT("Purifier"),
		TEXT("Fan Of Asheron"),
		TEXT("Asherons1"),
		TEXT("Shutterbug"),
		TEXT("The Focused"),
		TEXT("Dereth Recruiter"),
		TEXT("Fowl Follower"),
		TEXT("Followerof Asheron"),
		TEXT("Follows Directions"),
		TEXT("Cant Follow Directions"),
		TEXT("Likes Asheron"),
		TEXT("Likes Getting Titles"),
		TEXT("Likes Where This Is Going"),
		TEXT("Likes Ulgrim"),
		TEXT("Likable"),
		TEXT("Captivating"),
		TEXT("Masterof Ceremony"),
		TEXT("Road Warrior"),
		TEXT("Thriller"),
		TEXT("Haunts Your Dreams"),
		TEXT("Asherons Collect Caller"),
		TEXT("The Inquisitive"),
		TEXT("Portal Stormer"),
		TEXT("Bringerof Pain"),
		TEXT("Harbingerof Madness"),
		TEXT("Marked By Luck"),
		TEXT("Marked By Fate"),
		TEXT("Marked By Fame"),
		TEXT("Marked By Glamour"),
		TEXT("Marked By Bacon"),
		TEXT("Puzzlemaster"),
		TEXT("Riddle Ravager"),
		TEXT("The Cool Kids Club"),
		TEXT("Epic Win"),
		TEXT("Epic Fail"),
		TEXT("Always Picked First"),
		TEXT("Always Picked Last"),
		TEXT("Forever Alone"),
		TEXT("Ninety Nine Problems Olthoi Ate1"),
		TEXT("Hungryfor Moar"),
		TEXT("I Can Haz Title Nao"),
		TEXT("Snowbunny"),
		TEXT("Cold As Ice"),
		TEXT("Penguin Plunge"),
		TEXT("Flower Sniffer"),
		TEXT("Springs Into Action"),
		TEXT("Heats Things Up"),
		TEXT("Cruel Summer"),
		TEXT("Hotinthe City"),
		TEXT("Runs Through Sprinklers"),
		TEXT("The Knowledgeable"),
		TEXT("Well Trained"),
		TEXT("Pumpkin Lord"),
		TEXT("Haunted"),
		TEXT("Possessed"),
		TEXT("Doomsayer"),
		TEXT("Accursed"),
		TEXT("Cold Turkey"),
		TEXT("Jive Turkey"),
		TEXT("Present Protector"),
		TEXT("Holly Jolly Helper"),
		TEXT("Loss Prevention"),
		TEXT("Christmas Courier"),
		TEXT("Holiday Hero"),
		TEXT("Crown Of The Deru"),
		TEXT("Viridian Dreamer"),
		TEXT("Viridian Lord"),
		TEXT("Viridian Knight"),
		TEXT("Viridian Stalker"),
		TEXT("Viridian Slayer"),
		TEXT("Viridian Purifier"),
		TEXT("Knight Of Thorns"),
		TEXT("Hunter Of Thorns"),
		TEXT("Mage Of Thorns"),
		TEXT("Thornstalker"),
		TEXT("Champion Of The Viridian Tree"),
		TEXT("Corruptor Of The Root"),
		TEXT("Killer Among Shadows"),
		TEXT("Servant Of The Vile"),
		TEXT("Knight Of Corrupted Amber"),
		TEXT("Gauntlet Champion"),
		TEXT("Bloodthirsty"),
		TEXT("Gauntlet Gladiator"),
		TEXT("Wily Warrior"),
		TEXT("Soldier Of Fortune"),
		TEXT("Society Savage"),
		TEXT("Coin Collector"),
		TEXT("Brutal Barbarian"),
		TEXT("Idolized"),
		TEXT("Master Of Puppets"),
		TEXT("Titan Slayer"),
		TEXT("Awakened"),
		TEXT("Enlightened"),
		TEXT("Illuminated"),
		TEXT("Transcended"),
		TEXT("Cosmic Conscious"),
		TEXT("Last Man Standing"),
	};
	const uint32 Count = UE_ARRAY_COUNT(Names);
	if (TitleId >= Count) return TEXT("(Unknown Title)");
	return Names[TitleId];
}
