// Auto-extracted from ACE.Entity WeenieError summaries (combat/UI relevant).
static const TMap<uint32, FString>& GetWeenieErrorStrings()
{
	static TMap<uint32, FString> Map;
	static bool bInit = false;
	if (!bInit)
	{
		bInit = true;
		Map.Add(0x042C, TEXT("Target not acquired."));
		Map.Add(0x044C, TEXT("That player is not accepting trade requests."));
		Map.Add(0x044D, TEXT("That player has squelched you."));
		Map.Add(0x044E, TEXT("You are too far away to trade."));
		Map.Add(0x044F, TEXT("You or that player are already trading."));
		Map.Add(0x0450, TEXT("That player is too busy to trade."));
		Map.Add(0x0451, TEXT("Trade closed."));
		Map.Add(0x0000, TEXT("No error (success)"));
		Map.Add(0x0017, TEXT("You failed to go to non-combat mode."));
		Map.Add(0x001D, TEXT("You're too busy!"));
		Map.Add(0x0020, TEXT("You must control both objects!"));
		Map.Add(0x0023, TEXT("Unable to move to object!"));
		Map.Add(0x0024, TEXT("You can't jump while in the air"));
		Map.Add(0x0026, TEXT("That is not a valid command."));
		Map.Add(0x0028, TEXT("The item is under someone else's control!"));
		Map.Add(0x0029, TEXT("You cannot pick that up!"));
		Map.Add(0x002A, TEXT("You are too encumbered to carry that!"));
		Map.Add(0x0036, TEXT("Action cancelled!"));
		Map.Add(0x0037, TEXT("Unable to move to object!"));
		Map.Add(0x0038, TEXT("Unable to move to object!"));
		Map.Add(0x0039, TEXT("Unable to move to object!"));
		// 0x003B ILeftTheWorld / 0x003C ITeleported — portal plumbing, not player-facing.
		Map.Add(0x003D, TEXT("You charged too far!"));
		Map.Add(0x003E, TEXT("You are too tired to do that!"));
		Map.Add(0x0048, TEXT("You can't jump from this position"));
		Map.Add(0x004A, TEXT("Ack! You killed yourself!"));
		Map.Add(0x004D, TEXT("Invalid PK Status!"));
		Map.Add(0x03EE, TEXT("The container is closed!"));
		Map.Add(0x03F1, TEXT("You failed to go to non-combat mode."));
		Map.Add(0x03F7, TEXT("You are too fatigued to attack!"));
		Map.Add(0x03F8, TEXT("You are out of ammunition!"));
		Map.Add(0x03F9, TEXT("Your missile attack misfired!"));
		Map.Add(0x03FA, TEXT("You've attempted an impossible spell path!"));
		Map.Add(0x03FC, TEXT("That spell cannot be cast that way."));
		Map.Add(0x03FE, TEXT("You don't know that spell!"));
		Map.Add(0x03FF, TEXT("Incorrect target type"));
		Map.Add(0x0401, TEXT("You don't have enough Mana to cast this spell."));
		Map.Add(0x04C8, TEXT("That item doesn't have enough mana!"));
		Map.Add(0x0400, TEXT("You don't have all the components for this spell."));
		Map.Add(0x0401, TEXT("You don't have enough Mana to cast this spell."));
		Map.Add(0x0402, TEXT("Your spell fizzled."));
		Map.Add(0x0403, TEXT("Your spell's target is missing!"));
		Map.Add(0x0404, TEXT("Your projectile spell mislaunched!"));
		Map.Add(0x0407, TEXT("Your spell cannot be cast outside"));
		Map.Add(0x0408, TEXT("Your spell cannot be cast inside"));
		Map.Add(0x040A, TEXT("You are unprepared to cast a spell"));
		Map.Add(0x040B, TEXT("You've already sworn your Allegiance"));
		Map.Add(0x040C, TEXT("You don't have enough experience available to swear Allegiance"));
		Map.Add(0x0414, TEXT("You are not in an allegiance!"));
		Map.Add(0x041D, TEXT("You must be the leader of a Fellowship"));
		Map.Add(0x041E, TEXT("Your Fellowship is full"));
		Map.Add(0x041F, TEXT("That Fellowship name is not permitted"));
		Map.Add(0x0422, TEXT("That channel doesn't exist."));
		Map.Add(0x0423, TEXT("You can't use that channel."));
		Map.Add(0x0424, TEXT("You're already on that channel."));
		Map.Add(0x0425, TEXT("You're not currently on that channel."));
		Map.Add(0x0426, TEXT("_ can't be dropped"));
		Map.Add(0x0427, TEXT("You cannot merge different stacks!"));
		Map.Add(0x0428, TEXT("You cannot merge enchanted items!"));
		Map.Add(0x0429, TEXT("You must control at least one stack!"));
		Map.Add(0x0432, TEXT("Your craft attempt fails."));
		Map.Add(0x0433, TEXT("Your craft attempt fails."));
		Map.Add(0x0434, TEXT("Given that number of items, you cannot craft anything."));
		Map.Add(0x0435, TEXT("Your craft attempt fails."));
		Map.Add(0x0438, TEXT("You do not have all the neccessary items."));
		Map.Add(0x0439, TEXT("Not all the items are avaliable."));
		Map.Add(0x043A, TEXT("You must be at rest in peace mode to do trade skills."));
		Map.Add(0x043B, TEXT("You are not trained in that trade skill."));
		Map.Add(0x043C, TEXT("Your hands must be free."));
		Map.Add(0x043D, TEXT("You cannot link to that portal!"));
		Map.Add(0x043E, TEXT("You have solved this quest too recently!"));
		Map.Add(0x043F, TEXT("You have solved this quest too many times!"));
		Map.Add(0x0445, TEXT("This item requires you to complete a specific quest before you can pick it up!"));
		Map.Add(0x045C, TEXT("Player killers may not interact with that portal!"));
		Map.Add(0x045D, TEXT("Non-player killers may not interact with that portal!"));
		Map.Add(0x045E, TEXT("You do not own a house!"));
		Map.Add(0x045F, TEXT("You do not own a house!"));
		Map.Add(0x0466, TEXT("You must purchase Asheron's Call: Dark Majesty to interact with that portal."));
		Map.Add(0x0469, TEXT("You have used all the hooks you are allowed to use for this house."));
		Map.Add(0x046A, TEXT("_ doesn't know what to do with that."));
		Map.Add(0x0474, TEXT("You must complete a quest to interact with that portal."));
		Map.Add(0x047F, TEXT("You must own a house to use this command."));
		Map.Add(0x0482, TEXT("Your monarch has closed the mansion to the Allegiance."));
		Map.Add(0x048A, TEXT("You must be a monarch to purchase this dwelling."));
		Map.Add(0x048E, TEXT("Your offer of Allegiance has been ignored."));
		Map.Add(0x048F, TEXT("You are already involved in something!"));
		Map.Add(0x0490, TEXT("You must be a monarch to use this command."));
		Map.Add(0x0491, TEXT("You must specify a character to boot. (From allegiance)"));
		Map.Add(0x0492, TEXT("You can't boot yourself! (From allegiance)"));
		Map.Add(0x0493, TEXT("That character does not exist."));
		Map.Add(0x0494, TEXT("That person is not a member of your Allegiance!"));
		Map.Add(0x0495, TEXT("No patron from which to break!"));
		Map.Add(0x0496, TEXT("Your Allegiance has been dissolved!"));
		Map.Add(0x0497, TEXT("Your patron's Allegiance to you has been broken!"));
		Map.Add(0x0498, TEXT("You have moved too far!"));
		Map.Add(0x0499, TEXT("That is not a valid destination!"));
		Map.Add(0x049A, TEXT("You must purchase Asheron's Call -- Dark Majesty to use this function."));
		Map.Add(0x049B, TEXT("You fail to link with the lifestone!"));
		Map.Add(0x049C, TEXT("You wandered too far to link with the lifestone!"));
		Map.Add(0x049D, TEXT("You successfully link with the lifestone!"));
		Map.Add(0x049E, TEXT("You must have linked with a lifestone in order to recall to it!"));
		Map.Add(0x049F, TEXT("You fail to recall to the lifestone!"));
		Map.Add(0x04A0, TEXT("You fail to link with the portal!"));
		Map.Add(0x04A1, TEXT("You successfully link with the portal!"));
		Map.Add(0x04A2, TEXT("You fail to recall to the portal!"));
		Map.Add(0x04A3, TEXT("You must have linked with a portal in order to recall to it!"));
		Map.Add(0x04A4, TEXT("You fail to summon the portal!"));
		Map.Add(0x04A5, TEXT("You must have linked with a portal in order to summon it!"));
		Map.Add(0x04A6, TEXT("You fail to teleport!"));
		Map.Add(0x04A7, TEXT("You have been teleported too recently!"));
		Map.Add(0x04A8, TEXT("You must be an Advocate to interact with that portal."));
		Map.Add(0x04AA, TEXT("Players may not interact with that portal."));
		Map.Add(0x04AB, TEXT("You are not powerful enough to interact with that portal!"));
		Map.Add(0x04AC, TEXT("You are too powerful to interact with that portal!"));
		Map.Add(0x04AD, TEXT("You cannot recall to that portal!"));
		Map.Add(0x04AE, TEXT("You cannot summon that portal!"));
		Map.Add(0x04AF, TEXT("The lock is already unlocked."));
		Map.Add(0x04B2, TEXT("The key doesn't fit this lock."));
		Map.Add(0x04B3, TEXT("The lock has been used too recently."));
		Map.Add(0x04B4, TEXT("You aren't trained in lockpicking!"));
		Map.Add(0x04B5, TEXT("You must specify a character to query."));
		Map.Add(0x04B6, TEXT("Please use the allegiance panel to view your own information."));
		Map.Add(0x04B7, TEXT("You have used that command too recently."));
		Map.Add(0x04BD, TEXT("You do not own that salvage tool!"));
		Map.Add(0x04BE, TEXT("You do not own that item!"));
		Map.Add(0x04C1, TEXT("The material cannot be created."));
		Map.Add(0x04C2, TEXT("The list of items you are attempting to salvage is invalid."));
		Map.Add(0x04C3, TEXT("You cannot salvage items that you are trading!"));
		Map.Add(0x04C4, TEXT("You must be a guest in this house to interact with that portal."));
		Map.Add(0x04C5, TEXT("Your Allegiance Rank is too low to use that item's magic."));
		Map.Add(0x04C7, TEXT("Your Arcane Lore skill is too low to use that item's magic."));
		Map.Add(0x04C8, TEXT("That item doesn't have enough Mana."));
		Map.Add(0x04CC, TEXT("You have been involved in a player killer battle too recently to do that!"));
		Map.Add(0x04D0, TEXT("You have failed to alter your skill."));
		Map.Add(0x04DC, TEXT("Appears to be sent to a recruiter 30 seconds after the initial recruit message when the recruitee doesn't respond."));
		Map.Add(0x04DD, TEXT("You have failed to alter your attributes."));
		Map.Add(0x04E0, TEXT("You are currently wielding items which require a certain level of skill. Your attributes cannot be transferred while you are wielding these items. Please remove these items and try again."));
		Map.Add(0x04E1, TEXT("You have succeeded in transferring your attributes!"));
		Map.Add(0x04E2, TEXT("This hook is a duplicated housing object. You may not add items to a duplicated housing object. Please empty the hook and allow it to reset."));
		Map.Add(0x04E3, TEXT("That item is of the wrong type to be placed on this hook."));
		Map.Add(0x04E4, TEXT("This chest is a duplicated housing object. You may not add items to a duplicated housing object. Please empty everything -- including backpacks -- out of the chest and allow the chest to reset."));
		Map.Add(0x04E5, TEXT("This hook was a duplicated housing object. Since it is now empty, it will be deleted momentarily. Once it is gone, it is safe to use the other, non-duplicated hook that is here."));
		Map.Add(0x04E6, TEXT("This chest was a duplicated housing object. Since it is now empty, it will be deleted momentarily. Once it is gone, it is safe to use the other, non-duplicated chest that is here."));
		Map.Add(0x04E7, TEXT("You cannot swear allegiance to anyone because you own a monarch-only house. Please abandon your house and try again."));
		Map.Add(0x04EB, TEXT("You can't do that while in the air!"));
		Map.Add(0x04EC, TEXT("You cannot modify your player killer status while you are recovering from a PK death."));
		Map.Add(0x04ED, TEXT("Advocates may not change their player killer status!"));
		Map.Add(0x04EE, TEXT("Your level is too low to change your player killer status with this object."));
		Map.Add(0x04EF, TEXT("Your level is too high to change your player killer status with this object."));
		Map.Add(0x04F0, TEXT("You feel a harsh dissonance, and you sense that an act of killing you have committed recently is interfering with the conversion."));
		Map.Add(0x04F1, TEXT("Bael'Zharon's power flows through you again. You are once more a player killer."));
		Map.Add(0x04F2, TEXT("Bael'Zharon has granted you respite after your moment of weakness. You are temporarily no longer a player killer."));
		Map.Add(0x04F3, TEXT("Lite Player Killers may not interact with that portal!"));
		Map.Add(0x04FC, TEXT("You aren't trained in healing!"));
		Map.Add(0x04FD, TEXT("You don't own that healing kit!"));
		Map.Add(0x04FE, TEXT("You can't heal that!"));
		Map.Add(0x0500, TEXT("You aren't ready to heal!"));
		Map.Add(0x0501, TEXT("You can only use Healing Kits on player characters."));
		Map.Add(0x0502, TEXT("The Lifestone's magic protects you from the attack!"));
		Map.Add(0x0503, TEXT("The portal's residual energy protects you from the attack!"));
		Map.Add(0x0504, TEXT("You are enveloped in a feeling of warmth as you are brought back into the protection of the Light. You are once again a Non-Player Killer."));
		Map.Add(0x0505, TEXT("You're too close to your sanctuary!"));
		Map.Add(0x0506, TEXT("You can't do that -- you're trading!"));
		Map.Add(0x0507, TEXT("Only Non-Player Killers may enter PK Lite. Please see @help pklite for more details about this command."));
		Map.Add(0x0508, TEXT("A cold wind touches your heart. You are now a Player Killer Lite."));
		Map.Add(0x050F, TEXT("You do not belong to a Fellowship."));
		Map.Add(0x0512, TEXT("You are now using the maximum number of hooks.  You cannot use another hook until you take an item off one of your hooks."));
		Map.Add(0x0513, TEXT("You are no longer using the maximum number of hooks.  You may again add items to your hooks."));
		Map.Add(0x0516, TEXT("You are not permitted to use that hook."));
		Map.Add(0x0519, TEXT("The fellowship is locked, you were not added to the fellowship."));
		Map.Add(0x051A, TEXT("Only the original owner may use that item's magic."));
		Map.Add(0x051D, TEXT("Turbine Chat is enabled."));
		Map.Add(0x0520, TEXT("You cannot add anymore people to the list of players that you can hear."));
		Map.Add(0x0523, TEXT("You are now deaf to player's screams."));
		Map.Add(0x0524, TEXT("You can hear all players once again."));
		Map.Add(0x0526, TEXT("You chicken out."));
		Map.Add(0x0527, TEXT("You cannot posssibly succeed."));
		Map.Add(0x0528, TEXT("The fellowship is locked; you cannot open locked fellowships."));
		Map.Add(0x0529, TEXT("Trade Complete!"));
		Map.Add(0x052A, TEXT("That is not a salvaging tool."));
		Map.Add(0x052B, TEXT("That person is not available now."));
		Map.Add(0x0532, TEXT("You must wait 30 days after purchasing a house before you may purchase another with any character on the same account. This applies to all housing except apartments."));
		Map.Add(0x0535, TEXT("You do not have the authority within your allegiance to do that."));
		Map.Add(0x0540, TEXT("You have the maximum number of accounts banned.!"));
		Map.Add(0x0545, TEXT("You already have the maximum number of allegiance officers. You must remove some before you add any more."));
		Map.Add(0x0546, TEXT("Your allegiance officers have been cleared."));
		Map.Add(0x0548, TEXT("You cannot join any chat channels while gagged."));
		Map.Add(0x054A, TEXT("You are no longer an allegiance officer."));
		Map.Add(0x054C, TEXT("Your allegiance does not have a hometown."));
		Map.Add(0x054E, TEXT("The hook does not contain a usable item. You cannot open the hook because you do not own the house to which it belongs."));
		Map.Add(0x054F, TEXT("The hook does not contain a usable item. Use the '@house hooks on'command to make the hook openable."));
		Map.Add(0x0550, TEXT("Out of Range!"));
		Map.Add(0x0552, TEXT("You must purchase Asheron's Call -- Throne of Destiny to use this function."));
		Map.Add(0x0553, TEXT("You must purchase Asheron's Call -- Throne of Destiny to use this item."));
		Map.Add(0x0554, TEXT("You must purchase Asheron's Call -- Throne of Destiny to use this portal."));
		Map.Add(0x0555, TEXT("You must purchase Asheron's Call -- Throne of Destiny to access this quest."));
		Map.Add(0x0556, TEXT("You have failed to complete the augmentation."));
		Map.Add(0x0557, TEXT("You have used this augmentation too many times already."));
		Map.Add(0x0558, TEXT("You have used augmentations of this type too many times already."));
		Map.Add(0x0559, TEXT("You do not have enough unspent experience available to purchase this augmentation."));
		Map.Add(0x055D, TEXT("You must exit the Training Academy before that command will be available to you."));
		Map.Add(0x055F, TEXT("Only Player Killer characters may use this command!"));
		Map.Add(0x0560, TEXT("Only Player Killer Lite characters may use this command!"));
		Map.Add(0x0561, TEXT("You may only have a maximum of 50 friends at once. If you wish to add more friends, you must first remove some."));
		Map.Add(0x0563, TEXT("That character is not on your friends list!"));
		Map.Add(0x0564, TEXT("Only the character who owns the house may use this command."));
		Map.Add(0x0565, TEXT("That allegiance name is invalid because it is empty. Please use the @allegiance name clear command to clear your allegiance name."));
		Map.Add(0x0566, TEXT("That allegiance name is too long. Please choose another name."));
		Map.Add(0x0567, TEXT("That allegiance name contains illegal characters. Please choose another name using only letters, spaces, - and '."));
		Map.Add(0x0568, TEXT("That allegiance name is not appropriate. Please choose another name."));
		Map.Add(0x0569, TEXT("That allegiance name is already in use. Please choose another name."));
		Map.Add(0x056B, TEXT("Your allegiance name has been cleared."));
		Map.Add(0x056C, TEXT("That is already the name of your allegiance!"));
		Map.Add(0x056F, TEXT("That is an invalid officer level."));
		Map.Add(0x0570, TEXT("That allegiance officer title is not appropriate."));
		Map.Add(0x0571, TEXT("That allegiance name is too long. Please choose another name."));
		Map.Add(0x0572, TEXT("All of your allegiance officer titles have been cleared."));
		Map.Add(0x0573, TEXT("That allegiance title contains illegal characters. Please choose another name using only letters, spaces, - and '."));
		Map.Add(0x0579, TEXT("You have not pre-approved any vassals to join your allegiance."));
		Map.Add(0x057C, TEXT("You have cleared the pre-approved vassal for your allegiance."));
		Map.Add(0x057D, TEXT("That character is already gagged!"));
		Map.Add(0x057E, TEXT("That character is not currently gagged!"));
		Map.Add(0x0581, TEXT("Your allegiance chat privileges have been restored."));
		Map.Add(0x0584, TEXT("You cannot pick up more of that item!"));
		Map.Add(0x0585, TEXT("You are restricted to clothes and armor created for your race."));
		Map.Add(0x0586, TEXT("That item was specifically created for another race."));
		Map.Add(0x0587, TEXT("Olthoi cannot interact with that!"));
		Map.Add(0x0588, TEXT("Olthoi cannot use regular lifestones! Asheron would not allow it!"));
		Map.Add(0x0589, TEXT("The vendor looks at you in horror!"));
		Map.Add(0x058B, TEXT("As a mindless engine of destruction an Olthoi cannot join a fellowship!"));
		Map.Add(0x058C, TEXT("The Olthoi only have an allegiance to the Olthoi Queen!"));
		Map.Add(0x058D, TEXT("You cannot use that item!"));
		Map.Add(0x058E, TEXT("This person will not interact with you!"));
		Map.Add(0x058F, TEXT("Only Olthoi may pass through this portal!"));
		Map.Add(0x0590, TEXT("Olthoi may not pass through this portal!"));
		Map.Add(0x0591, TEXT("You may not pass through this portal while Vitae weakens you!"));
		Map.Add(0x0593, TEXT("Olthoi characters can only use Lifestone and PK Arena recalls!"));
	}
	return Map;
}
