[/Script/Engine.GameUserSettings]
; Prefer the desktop's native resolution in fullscreen / windowed fullscreen.
bUseVSync=False
FullscreenMode=1
LastConfirmedFullscreenMode=1
PreferredFullscreenMode=1
bUseDesktopResolutionInFullscreen=True
FrameRateLimit=0.000000
DesiredScreenWidth=1920
DesiredScreenHeight=1080
LastUserConfirmedDesiredScreenWidth=1920
LastUserConfirmedDesiredScreenHeight=1080
ResolutionSizeX=1920
ResolutionSizeY=1080
LastUserConfirmedResolutionSizeX=1920
LastUserConfirmedResolutionSizeY=1080
Version=5
